<?php defined('BASEPATH') or exit('No direct script access allowed');

class Migration_create_products extends CI_Migration
{

	public function up()
	{
		## Create Table products
		$this->dbforge->add_field(
			array(
				'item_id' => array('type' => 'int', 'key' => TRUE, 'auto_increment' => TRUE),
				'sku' => array('type' => 'varchar', 'constraint' => '50', 'null' => TRUE),
				'slug' => array('type' => 'text', 'constraint' => '65535', 'null' => TRUE),
				'name' => array('type' => 'varchar', 'constraint' => '100', 'null' => TRUE),
				'description' => array('type' => 'text', 'constraint' => '65535', 'null' => TRUE),
				'created_at' => array('type' => 'datetime', 'null' => TRUE),
				'updated_at' => array('type' => 'datetime', 'null' => TRUE),
				'price' => array('type' => 'double', 'null' => TRUE),
				'discount' => array('type' => 'double', 'null' => TRUE),
				'f_category_code' => array('type' => 'varchar', 'constraint' => '30', 'null' => TRUE),
				'f_sub_category_code' => array('type' => 'varchar', 'constraint' => '30', 'null' => TRUE),
				'stock' => array('type' => 'int', 'null' => TRUE),
				'weight' => array('type' => 'double', 'null' => TRUE)
			)
		);
		$this->dbforge->add_key("item_id", true);

		$this->dbforge->create_table("products", TRUE);
		$this->db->query('ALTER TABLE  `products` ENGINE = InnoDB');
		## Generate Table Data 
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (11, '11111', 'running-jersey-dk-basic-color-tee-man-tosca-m', 'Running Jersey - DK Basic Color Tee Man Tosca - M', '- Cocok digunakan untuk short run, gym & fitness, outdoor activities, dll\\r\\n- Sangat nyaman digunakan sebagai daily activities\\r\\n- Terbuat dari 92% micro fiber polyester & 8% spandex\\r\\n- Dilengkapi high tech fabric dari HeiQ Materials AG dengan fitur Smart Temp, Fresh Tech & Sun Blocks UPF 50\\r\\n- Dirancang regular fit mengikuti bentuk tubuh\\r\\n\\r\\nRunning Jersey dari DK Outdoor & Sports dilengkapi HeiQ Technology dari perusahaan HeiQ Materials AG, perusahaan asal Swiss yang terdepan mengembangkan material jersey berinovasi teknologi (High Tech Fabric).\\r\\nHigh tech fabric dari HeiQ Materials AG pada running jersey DK Outdoor & Sports yaitu\\r\\n\\r\\n#1. SMART TEMP – Teknologi ini mendinginkan suhu ketika suhu lingkungan panas, dan sebaliknya sehingga kamu tetap nyaman & sejuk. Yang pasti aman untuk kulit Anda.\\r\\n\\r\\n#2. FRESH TECH - Teknologi pada running jersey DK Outdoor & Sports jersey yang bisa menjaga kesegaran dan kontrol bau dari bau lingkungan, bau kain, bau badan hormonal, bau badan terkait makanan, dan bau dari bakteri.\\r\\n\\r\\n#3. SUN BLOCKS UPF 50 - Teknologi HeiQ Sun Blocks dengan military grade UPF 50, lebih baik untuk perlindungan tahan lama dari sinar UV dibanding lainnya yang hanya UPF 30+.\\r\\n\\r\\nSemakin stylish, keren, dan percaya diri dengan design – design running jersey dari DK Outdoor & Sports untuk berlari, outdoor activity ataupun daily activity. Untuk menjaga kualitas produk agar tahan lama sangat direkomendasikan untuk tidak mencucinya menggunakan pelembut (softener).', NULL, NULL, 229000, 120000, 'pakaian', 'pakaian-olahraga', 10, 300);");
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (13, '111112', 'duraking-jas-hujan-imvula-black-l', 'Duraking Jas Hujan Imvula - Black, L', 'Duraking Imvula Raincoat - Jas hujan (jaket dan celana) yang di design trendy dan nyaman dikenakan untuk melindungi aktivitas luar ruangan saat cuaca hujan. Material 2 layers coat fabric yang bersifat waterproof dan windproof melindungi dari basahnya air hujan dan dinginnya angin. Jas hujan Duraking tidak kaku (elastis), halus dan tidak mudah robek. Mudah untuk dibawa dan dapat dipakai berulang kali. Cocok untuk berkendara sepeda motor, dalam keadaan darurat atau pun untuk travelling.\\r\\n\\r\\n1. Waterproof\\r\\nTidak tembus air\\r\\n\\r\\n2. Windproof\\r\\nKemampuan menahan angin\\r\\n\\r\\nMaterial : 2 layers coat\\r\\nInclude : Jaket dan celana\\r\\n\\r\\nDeskripsi Size Chart Jas Hujan Imvula Raincoat\\r\\nUkuran | Lebar Dada | Panjang Badan | Lingkar Pinggang (Celana) | Panjang Celana\\r\\nL | 61.5 | 73 | 60 | 100\\r\\nXL | 65 | 76 | 62 | 102', NULL, NULL, 400000, 200000, 'pakaian', 'pakaian-olahraga', 15, 400);");
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (14, '111113', 'duraking-jersey-sepeda-gradient-series', 'Duraking Jersey Sepeda Gradient Series', 'Duraking meluncurkan inovasi terbaru. Kini dengan cutting baru yang di design aero-dinamis. Membuat ini lebih pas di badan sehingga lebih terasa dinamis saat dipakai bersepeda. Berbahan kain Duraking Super Lightweight yang ringan dan sejuk. Dengan fitur-fitur terbaru yang dilengkapi dengan Safety Pocket yang memungkinkan menyimpan barang pada saku menjadi lebih aman. Karet Gripper pada bagian bawah jersey membuatnya tidak mudah terangkat saat membungkuk. Reflector yang terdapat pada jersey ini membuat kamu semakin aman lagi saat berkendara dimalam hari.\\r\\n\\r\\nDuraking Cycling Jersey ini dilengkapi teknologi :\\r\\n\\r\\n\\r\\n1.DK V ProTech\\r\\n\\r\\nTeknologi AntiVirus yang dapat membunuh virus, bakteri dan jamur dalam hitungan detik dengan menyerang membran pelindung sel virus saat bersentuhan dengan kain.\\r\\n\\r\\n\\r\\n2.DK Dry Tech\\r\\n\\r\\nTeknologi cepat kering “Quick Dry” yang diinjeksi yang bersifat permanent, membuat kain lebih cepat kering dan mampu merespon panas untuk menyesuaikan suhu. Teknologi ini mampu menurunkan suhu hingga 2,5 derajat Celcius, begitu juga pada kondisi sebaliknya.\\r\\n\\r\\n\\r\\n3.DK UV ProTech\\r\\n\\r\\nTeknologi perlindungan Anti UV permanen yang diinjeksi pada tiap helai kainnya membuatmu terlindungi dari bahaya paparan sinar UV A dan UV B. Dengan UPF 50+ (setara military grade) membuatmu merasa aman saat beraktifitas diluar ruangan.', NULL, NULL, 250000, 50000, 'pakaian', 'pakaian-olahraga', 19, 300);");
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (15, '111114', 'jersey-dk-super-light-series', 'Jersey DK Super Light Series', 'Mudah lelah karena baju terasa berat? Atau mudah bau karena pakaian menyerap banyak keringat? DK SUPER LIGHT SERIES hadir untuk meringankan bebanmu saat beraktivitas dengan teknologi jersey terbaru!\\r\\n\\r\\nMeringankan aktivitasmu dengan fitur-fitur terbaru:\\r\\n#1. DK SUPERLIGHT TECH -\\r\\nMaterial sangat ringan, 92% microfiber polyester & 8% spandex\\r\\n\\r\\n#2. DK DRY TECH -\\r\\nTeknologi cepat kering permanen dan mampu menyesuaikan suhu agar tetap sejuk\\r\\n\\r\\n#3. DK UV Pro-Tech -\\r\\nTeknologi Anti UV UPF 50+ permanen yang diinjeksi pada tiap helai benang\\r\\n\\r\\n#4. DK Fresh Tech -\\r\\nMenjaga kesegaran dan kontrol bau dari bau badan hormonal saat beraktivitas\\r\\n\\r\\nDK SUPER LIGHT SERIES cocok untuk segala jenis aktivitas seperti olahraga, kegiatan outdoor, ataupun dipakai sehari-hari.\\r\\n\\r\\nDirancang REGULAR FIT mengikuti bentuk tubuh, membuat kamu tetap stylish dan percaya diri.', NULL, NULL, 100000, 10000, 'pakaian', 'pakaian-olahraga', 25, 500);");
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (16, '111115', 'kaos-polos-pria-cotton-combed-30s-reguler', 'KAOS POLOS PRIA COTTON COMBED 30S REGULER', '1.Abu Tua : S M L XL XXL 3XL 4XL\\r\\n2.Maroon Tua : S M L XL XXL 3XL 4XL\\r\\n3.Putih Solid : S M L XL XXL 3XL 4XL\\r\\n4.Hitam Solid : S M L XL XXL 3XL 4XL\\r\\n5.Mustard : S M L XL XXL 3XL 4XL\\r\\n6.Navy Tua : S M L XL XXL 3XL 4XL\\r\\n7.Hijau Army : S M L XL XXL 3XL 4XL\\r\\n8.Merah Solid : S M L XL XXL 3XL 4XL\\r\\n9.Abu Misty : S M L XL XXL 3XL 4XL\\r\\n10.Biru Turkish : S M L XL XXL 3XL 4XL\\r\\n11.Biru Benhur : S M L XL XXL 3XL 4XL\\r\\n12.Hijau Botol : S M L XL XXL 3XL 4XL\\r\\n13.Orange : S M L XL XXL 3XL 4XL\\r\\n14.Pink Baby : S M L XL XXL 3XL 4XL\\r\\n15.Kuning Kenari : S M L XL XXL 3XL 4XL\\r\\n16.Coklat Tua : S M L XL 3XL 4XL\\r\\n17.Biru Baby : S M L XL XXL 3XL 4XL\\r\\n18.Tosca : S M L XL XXL 3XL 4XL\\r\\n19.Cream : S M L XL XXL 3XL 4XL\\r\\n20.Fanta : S M L XL XXL 3XL 4XL\\r\\n21.Ungu Muda : S M L XL XXL 3XL 4XL\\r\\n22.Teracota : S M L XL XXL 3XL 4XL\\r\\n23.Dusty Pink : S M L XL XXL 3XL 4XL\\r\\n24.Hijau Neon : S M L XL XXL 3XL 4XL\\r\\n\\r\\n.\\r\\n\\r\\nSpesifikasi Produk :\\r\\n- Model : O neck short sleeve\\r\\n- Pola : Reguler Fit\\r\\n- Gender : Unisex\\r\\n\\r\\n- Kain : 100% cotton combed 30s\\r\\n- Handfeel : Supersoft\\r\\n- Gramasi : 150-160 gr/m2\\r\\n\\r\\n- Baju dibungkus plastik opp satuan\\r\\n- New tshirt pattern (pola standar Uniql*)\\r\\n- Label size ada, Polos tanpa logo brand\\r\\n\\r\\n.\\r\\n\\r\\nSpesifikasi Jahitan :\\r\\n- Pundak jahit double rantai\\r\\n- BIS jahit double stick\\r\\n- Obras rapi dan kuat\\r\\n\\r\\nStandar baru mulai September 2020 :\\r\\n- RIP jahit double stick\\r\\n- Sambungan RIP rata\\r\\n- Overdeck jahit 3 jarum\\r\\n- Kualitas standar brand', NULL, NULL, 30000, 5000, 'pakaian', 'kaos-pria', 30, 350);");
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (17, '111116', 'kaos-polos-baju-pria-kaos-pria-premium-cotton-kaos-lengan-pendek', 'Kaos Polos Baju Pria Kaos Pria Premium Cotton Kaos Lengan Pendek', 'SIZE CHART ( Ukuran Baju ) ada pada HALAMAN BERIKUTNYA DI FOTO produk kami.\\r\\n\\r\\nUNTUK WARNA PRODUK HARAP MEMESAN DI IKLAN YANG BERSANGKUTAN\\r\\n\\r\\nCONTOH :\\r\\n\\r\\nAPABILA ANDA MEMESAN WARNA PUTIH DI IKLAN WARNA HITAM. MAKA AKAN KAMI KIRIMKAN WARNA HITAM!\\r\\n\\r\\nHARAP DIPERHATIKAN!! SIZE KAMI LEBIH BESAR!!\\r\\n\\r\\nHATI HATI DENGAN PENJUAL YANG MENJUAL DENGAN HARGA MURAH NAMUN SIZE LEBIH KECIL!\\r\\n\\r\\nSIZE CHART :\\r\\n\\r\\nPAJANG X LEBAR\\r\\n\\r\\nS = 66 CM X 47 CM\\r\\nM = 70 CM X 49 CM\\r\\nL = 72 CM X 52 CM\\r\\nXL = 75 CM X 55 CM\\r\\n\\r\\nSEMUA WARNA YANG TAYANG PADA IKLAN KAMI ARTINYA READY STOCK!', NULL, NULL, 25000, 5000, 'pakaian', 'kaos-pria', 15, 250);");
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (18, '111117', 'kaos-custom-sablon-polyflex-tulisan-suka-suka-cotton-combed-30s', 'KAOS CUSTOM SABLON POLYFLEX TULISAN SUKA SUKA COTTON COMBED 30S', 'Bahan kaos full cotton combed 30s (garansi)\\r\\nSablon 1 warna, tambah warna kena tambahan\\r\\nPosisi sablon standar dada depan\\r\\nBisa request posisi sablon bebas\\r\\n\\r\\nVarian 1 baris 29 x 10 cm:\\r\\nKhusus teks maksimal 15 huruf, font dipilih dari tabel\\r\\nCARA ORDER: Warna baju - Ukuran - Tulisan - Kode Font - Warna sablon\\r\\nCONTOH: Kuning - L - Tulisankamu - 26 - Pink Gum\\r\\n\\r\\nVarian 2 baris 29 x 15 cm:\\r\\nKhusus teks maksimal 30 huruf, font dipilih dari tabel\\r\\nCARA ORDER: Warna baju - Ukuran - (B1)Tulisan (B2)Tulisan - Kode Font - Warna sablon\\r\\nCONTOH: Kuning - L - (B1) Atas (B2) Bawah - 26 - Pink Gum\\r\\n\\r\\nSupreme 1 warna 29 x 10 cm:\\r\\nKhusus teks maksimal 15 huruf, font Supreme / pilih dari tabel\\r\\nCARA ORDER: Warna baju - Ukuran - Tulisan - Kode Font - Warna kotak\\r\\nCONTOH: Kuning - L - Tulisankamu - 26 - Pink Gum\\r\\n\\r\\nSupreme 2 warna 29 x 10 cm:\\r\\nKhusus teks maksimal 15 huruf, font Supreme / pilih dari tabel\\r\\nCARA ORDER: Warna baju - Ukuran - Tulisan - Kode Font - Warna kotak - Warna tulisan\\r\\nCONTOH: Kuning - L - Tulisankamu - 26 - (Kotak) Pink Gum - (Tulisan) Putih\\r\\n\\r\\nRequest Vs Request:\\r\\nKhusus teks maksimal 15 huruf tiap baris, font tidak bisa pilih\\r\\nCARA ORDER: Warna baju - Ukuran - Tulisan Vs Tulisan - Warna sablon\\r\\nCONTOH: Kuning - L - Atas Vs Bawah - Pink Gum\\r\\n\\r\\nVarian A5: 29 x 10 cm atau 15 x 20 cm\\r\\nBisa teks atau gambar 1 warna\\r\\nTeks maksimal 25 huruf, font bebas bisa request dafont\\r\\nCARA ORDER VIA CHAT TOKOPEDIA\\r\\n\\r\\nVarian A4: 20 x 29 cm, bisa berdiri atau tidur\\r\\nBisa teks atau gambar 1 warna\\r\\nTeks maksimal 50 huruf, font bebas bisa request dafont\\r\\nCARA ORDER VIA CHAT TOKOPEDIA\\r\\n\\r\\nVarian A3: 29 x 41 cm\\r\\nBisa teks atau gambar 1 warna\\r\\nTeks maksimal 100 huruf, font bebas bisa request dafont', NULL, NULL, 40000, 5000, 'pakaian', 'kaos-pria', 30, 150);");
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (19, '1111118', 'celana-jeans-panjang-pria-premium', 'CELANA JEANS PANJANG PRIA PREMIUM', 'CELANA JEANS PANJANG PRIA PREMIUM\\r\\n\\r\\nmatt : JEANS STRECH SAKURA\\r\\nLONG JEANS\\r\\n\\r\\nSedia size\\r\\n27-38\\r\\n\\r\\n28 LP 76 cm\\r\\n29 LP 78 cm\\r\\n30 LP 80 cm\\r\\n31 LP 82 cm\\r\\n32 LP 84 cm\\r\\n33 LP 86 cm\\r\\n34 LP 88 cm\\r\\n35 LP 90 cm\\r\\n36 LP 92 cm\\r\\n37 LP 95 cm\\r\\n38 LP 98 cm\\r\\n\\r\\nPJ 96/97 CM\\r\\n', NULL, NULL, 100000, 20000, 'celana', 'celana-jeans', 14, 600);");
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (20, '1111134', 'celana-panjang-slim-fit-stretch-soft-jeans-pria-hitam', 'Celana Panjang Slim Fit Stretch Soft Jeans Pria Hitam', 'Nuber - Break your limit\\r\\nGunakan produk Nuber untuk menemani keseharianmu,\\r\\nBahan Produk Nuber menggunakan Produk Terbaik dan Ternyaman\\r\\nuntuk aksesoris seperti resliting dan kancing menggunakan YKK (tingkat kualitas terbaik)', NULL, NULL, 130000, 10000, 'celana', 'celana-jeans', 5, 300);");
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (21, '112313', 'blazer-modric-black-jas-pria-slimfit-formal', 'Blazer MODRIC BLACK - Jas Pria Slimfit Formal', 'Spec Blazer NI.KA.YU\\r\\n1. BAHAN ISTIMEWAH: HIGH TWIST TEBAL (BUKAN BAHAN DRILL)\\r\\n2. Model Semua SLIMFIT(Model-Model Korea)\\r\\n3. Lapisan Dalam: Full FURING TEBAL(Mengkilap)\\r\\n4. Pakai KAIN KERAS Jadi Seperti JAS FORMAL\\r\\n5. Pundak Pakai BUSA BAGUS\\r\\n6. Saku Atas 1pcs+Saku Dalam 1pcs+Saku Bawah 2pcs\\r\\n7. Lengan Bawah ada Kancing3-4pcs\\r\\n8. Cocok utk Acara FORMAL dan SEMI FORMAL\\r\\n9. Tersedia: S M L XL\\r\\n\\r\\nDetail ukuran:\\r\\nSize S :\\r\\nLebar Dada 51cm(Lingkardada 102cm) dari ketiak Kanan-Kiri)\\r\\nPanjang 68cm(dari Ujung Kerah ke Bawah)\\r\\nLebar bahu 43cm\\r\\nPanjang Tangan 58cm\\r\\n\\r\\nSize M :\\r\\nLebar Dada 53cm (Lingkardada 106cm)\\r\\nPanjang 69cm\\r\\nLebar bahu 45cm\\r\\nPanjang Tangan 59cm\\r\\n\\r\\nSize L :\\r\\nLebar Dada 56cm (Lingkardada 112cm)\\r\\nPanjang 70cm\\r\\nLebar bahu 48cm\\r\\nPanjang Tangan 60cm\\r\\n\\r\\nSize XL :\\r\\nLebar Dada 58cm (Lingkardada 116cm)\\r\\nPanjang 73cm\\r\\nLebar bahu 50cm\\r\\nPanjang Tangan 61cm\\r\\n\\r\\nPREDIKSI\\r\\nS: Tinggi Badan150-165cm-Berat Badan 40-50kg\\r\\nM: Tinggi Badan160-170cm-Berat Badan 50-60kg\\r\\nL: Tinggi Badan170-175cm-Berat Badan 60-70kg\\r\\nXL Tinggi Badan175-185cm-Berat Badan 70-75kg', NULL, NULL, 230000, 20000, 'pakaian', 'blazer', 25, 250);");
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (22, '123132', 'dasi-instant-salur-langsung-pakai-kretekan-import-distributor-dasi', 'dasi instant salur langsung pakai kretekan import distributor dasi', 'Simpul sudah jahit paten\\r\\nDilengkapi velcro / prepetan\\r\\nbahan 100% polyester import\\r\\npanjang sekitar 50 cm, lebar sekitar 7-8 cm\\r\\nPilihan warna tidak banyak, silahkan chat utk ketersediaan stok\\r\\n\\r\\nButuh dasi? Langsung aja beli di distributornya\\r\\n\\r\\nmenjual juga suspender, dasi polos, penjepit dasi, topi golf, dasi gift box, dasi batik, dasi rohani, dll\\r\\n\\r\\nperlu diketahui toko kami di tokopedia hanya yang bernama distributor dasi, selain toko itu kami tidak bertanggung jawab atas semua penipuan, ketidak samaan barang dengan iklan atau kerusakan dasi yang dibeli selain di toko kami\\r\\n\\r\\nhanya di toko kami, kami berani menjamin garansi barang tanpa cacat , barang sesuai iklan', NULL, NULL, 35000, 10000, 'aksesoris', 'dasi', 40, 150);");
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (23, '212333', 'kaos-kaki-pendek-nike-original-100', 'Kaos Kaki Pendek Nike Original 100%', '???? KAOS KAKI NIKE ORIGINAL TERMURAH! ????\\r\\n\\r\\n\\r\\n✔️ NIKE ORIGINAL 100%!! Made in USA / Amerika Serikat! Bukan grade Ori lagi tapi memang Original\\r\\n\\r\\n???? Komposisi bahan: 68% Cotton, 31% Nylon, 1% Spandex', NULL, NULL, 35000, 0, 'aksesoris', 'kaos-kaki', 26, 200);");
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (24, '111163', 'ksl-masker-kn95-top-brand-top-quality-masker', 'KSL Masker KN95 Top brand Top Quality Masker', 'MEDICAL GRADE!!!!\\r\\n\\r\\nStock pasti ready!!!', NULL, NULL, 3000, 0, 'aksesoris', 'masker', 100, 50);");
		$this->db->query("INSERT INTO `products`(`item_id`, `sku`, `slug`, `name`, `description`, `created_at`, `updated_at`, `price`, `discount`, `f_category_code`, `f_sub_category_code`, `stock`, `weight`) VALUES (25, '111123', 'masker-medis-multi-one-plus-3-lapis-bundling-hand-sanitizer', 'Masker Medis Multi One Plus 3 Lapis Bundling Hand Sanitizer', 'Detail Bundling:\\r\\nMOP Surgical face mask box isi 50pcs & Aquatic Hand Anti-Bacterial Moisturizer Gel 100ml\\r\\n\\r\\nAquatic:\\r\\nFormulasi khusus dengan aroma yang menyegarkan serta tidak lengket di kulit dengan kemasan 100 mL yang mudah dibawa dan digunakan kapan pun dan dimana pun. Aquatic x Tokopedia Hand Moisturizer Gel siap menemani anda dan keluarga dengan perlindungan maksimal.\\r\\n\\r\\nKeunggulan:\\r\\nProduk ini memiliki fungsi utama sebagai moisturizer yang melembutkan kulit dan sebagai sanitizer dengan kandungan alkohol 70% yang melindungi kulit dari kuman dan bakteri.\\r\\n\\r\\nMOP mask 3 Ply :\\r\\nMasker yang dilengkapi dengan 3 lapis filter, membantu melindungi dari partikel makro dan debu. 1 pack terdiri dari 50 masker.\\r\\n\\r\\nAnjuran Pakai: Saat gejala flu,saat dekat bayi,saat bepergian.', NULL, NULL, 150000, 15000, 'aksesoris', 'masker', 10, 300);");
	}

	public function down()
	{
		### Drop table products ##
		$this->dbforge->drop_table("products", TRUE);
	}
}
